#!/usr/bin/env node --harmony

require('../src/global');

var cli = require('commander');
var yield = require('co');
var utils = base.require('core/utils');
var build = base.require('controllers/styles').build;

var styles;

cli
  .arguments('<styles...>')
  .action(function (arg) {
    styles = arg
  });

cli.parse(process.argv);

if (typeof styles === 'undefined') {
   console.error('no styles given!');
   process.exit(1);
}

yield(function * main() {
  var list = yield styles.map(function(style) {
    return { name: style }
  });
  yield * build(list);
  console.log('Generated', styles);
}).catch(function(err) {
  console.error('Failed to build. Error:', err);
  process.exit(1);
});
