#!/usr/bin/env node --harmony

require('../src/global');

var cli = require('commander');
var utils = base.require('core/utils');
var Style = base.require('controllers/styles/style');

var styles;

cli
  .arguments('<styles...>')
  .action(function (arg) ***REMOVED***
    styles = arg
***REMOVED***);

cli.parse(process.argv);

if (typeof styles === 'undefined') ***REMOVED***
   console.error('no styles given!');
   process.exit(1);
***REMOVED***

utils.yield(function * main() ***REMOVED***
  var styleDir	= base.path('styles');
  for (styleDetails of styles) ***REMOVED***
    var style = new Style(styleDetails, styleDir);
    yield * style.build();
    for (elementName of (yield style.getDefinition()).elements) ***REMOVED***
      yield * style.getElement(elementName);
***REMOVED***
    console.log('Generated', styleDetails);
***REMOVED***
***REMOVED***);
