#!/usr/bin/env node --harmony

require('../src/global');

var cli = require('commander');
var utils = base.require('core/utils');
var publish = base.require('core/publish');

var styles;

cli
  .arguments('<styles...>')
  .action(function (arg) {
     styles = arg;
  });

cli.parse(process.argv);

if (typeof styles === 'undefined') {
   console.error('no styles given!');
   process.exit(1);
}

var buildDir = 'src/client';

utils.glob('css/styles/**/styles.css', { cwd: buildDir })
  .then(function(files) {
    return publish(buildDir, files, { 'Content-Type': 'text/css' } )
  })
  .then(function() {
    return utils.glob('*(images|fonts)/*.*', { cwd: buildDir });
  })
  .then(function(files) {
    return publish(buildDir, files);
  })
  .then(function() {
    console.log('Finished publishing.');
  })
  .catch(function(error) {
    console.error('Failed to publish. Error:', error);
  });
