#!/usr/bin/env node --harmony

require('../src/global');

var cli = require('commander');
var utils = base.require('core/utils');
var publish = base.require('core/publish');

var styles;

cli
  .arguments('<styles...>')
  .action(function (arg) ***REMOVED***
     styles = arg;
***REMOVED***);

cli.parse(process.argv);

if (typeof styles === 'undefined') ***REMOVED***
   console.error('no styles given!');
   process.exit(1);
***REMOVED***

var buildDir = 'src/client';

var css = styles.map(function(style) ***REMOVED***
  return style + '/styles.css';
***REMOVED***);


publish(buildDir + '/css/styles', css)
  .then(function() ***REMOVED***
    return utils.glob('*(images|fonts)/*.*', ***REMOVED*** cwd: buildDir ***REMOVED***);
***REMOVED***)
  .then(function(files) ***REMOVED***
    return publish(buildDir, files);
***REMOVED***)
  .then(function() ***REMOVED***
    console.log('Finished publishing.');
***REMOVED***)
  .catch(function(error) ***REMOVED***
    console.error('Failed to publish. Error:', error);
***REMOVED***);
